// web-scraping-electron-app/renderer/src/components/Database.vue
<template>
  <div id="database-container" class="my-5 container">
    <h1 class="display-4">Database Information</h1>
    <p>Website Info</p>
  </div>
</template>

<script>
export default {
  name: "DatabasePage",
};
</script>

<style scoped>
/* Add specific styles for the Database component */
</style>

// frontend/vite-demo/src/components/Database.jsx
import React from 'react';
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap/dist/js/bootstrap.bundle.min.js';

export default function DatabasePage() {
  return (
    <div id="database-container" className="my-5 container">
      <h1 className="display-4">Database Information</h1>
      <p>Website Info</p>
    </div>
  );
}
